# Generated by Django 4.2.3 on 2023-07-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Produto')),
                ('disponivel', models.BooleanField(default=True)),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade no Estoque')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data criação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categoria')),
            ],
        ),
    ]
