# Generated by Django 4.2.3 on 2023-07-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_foto'),
        ('pedidos', '0002_remove_pedido_produtos_alter_pedido_total_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='pedidos.ItemPedido', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
